#!/bin/sh

export CASA=$( dirname $(readlink -f "$0") )
export CONDA="$CASA/conda"
export CASA_SRC="$CASA/src"

set -e
set -x

if [ ! -e "$CASA_SRC" ]; then
    mkdir "$CASA_SRC"
    "$CASA/setup_src"
fi



if [ ! -e "$CONDA" ]; then
    . "$CASA/setup_conda"
    "$CASA/setup_run_conda"
    "$CASA/setup_run_compiled"
    "$CASA/setup_dev_conda"
fi
